### ISSUE TITLE
tag 7.5.0-alpha4 grunt error

### ISSUE THREAD

**Issue by wexom** [camunda/camunda-bpm-webapp#7]
probably some errors with path in configs

[grunt_errors.txt](https://github.com/camunda/camunda-bpm-webapp/files/242798/grunt_errors.txt)

.

**Comment by jostsg** [comment]
Any news on this one or is there a workaround for the time being?

**Comment by SebastianStamm** [comment]
Does it still happen if you checkout the current master branch of the repo, re-install the node_modules and run grunt in the root directory?

If so, can you provide a guide how to reproduce it (preferably starting with "clone the camunda-bpm-webapp" repository)?

**Comment by jostsg** [comment]
Thanks for the quick reply. Using the documented versions of npm and node worked ;) It might make sense to add the engine restrictions to the package.json though.

**Comment by SebastianStamm** [comment]
Glad that it works for you now :) It would be awesome if you could provide a pull request with the improvements for the package.json
